# Generated by Django 5.1.3 on 2024-11-07 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("nome", models.CharField(max_length=100)),
                ("senha", models.CharField(max_length=255)),
                (
                    "profile",
                    models.URLField(default="https://via.placeholder.com/500x500"),
                ),
                ("logged_in", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="TweetModel",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("post", models.TextField()),
                ("image", models.URLField()),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tweets",
                        to="tweets_api.usermodel",
                    ),
                ),
            ],
        ),
    ]
