name: Deploy to Vercel

on:
  push:
    branches:
      - main

jobs:
  vercel-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Deploy to Vercel
        uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-project-name: tweeter-clone-api
          vercel-org-id: felipes-projects-554b7f45
          vercel-team-id: team_i5AagCA8nXUhqp2pTQFMjXcg
          vercel-project-id: dpl_4ZQuHxxmQYrdRhkEjXhqxtJKSrqK
          github-comment: true
          github-deployment: false
